/**
 * Live4.tv - Stream Networks API
 * Omnichannel for live streaming on social networks  We\'re glad that you chose to use Live4.tv\'s API for managing your connection with social networks (currently Instagram).            We understand that Instagram currently restricts users from conducting live broadcasts without their official app.           However, our innovative API empowers users to go live on Instagram without relying on the app itself.        By leveraging our API, users gain access to a stream key, enabling them to seamlessly transmit their live broadcasts using popular software like OBS (Open Broadcaster Software).        This breakthrough feature provides users with the freedom to connect with their audience and share captivating live content on Instagram, all without the constraints of the official app.  The login flow:  ![login flow image](https://api-stream-network.live4.tv/mermaid-diagram-login-flow.png \"Login flow image\") 
 *
 * OpenAPI spec version: 1.0
 * Contact: contato@live4.tv
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommentsResponse } from '../models/CommentsResponse';
import { HttpFile } from '../http/http';

export class GetCommentsResponse {
    /**
    * The live stream uuid
    */
    'uuid': string;
    /**
    * The total number of comments returned
    */
    'count': number;
    /**
    * The timestamp of the last comment returned. You can use it for the next request.
    */
    'lastCommentTimestamp': number;
    /**
    * An list of comments
    */
    'comments': Array<CommentsResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastCommentTimestamp",
            "baseName": "lastCommentTimestamp",
            "type": "number",
            "format": ""
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "Array<CommentsResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCommentsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

